@url = http://localhost:3000/api
@json = Content-Type: application/json
@cookie = Cookie: connect.sid=9wsEYgCPbUTkhpKt1NrN9mFsqmcapNTGfg

### regsiter
POST {{url}}/register
{{json}}

{
  "uname": "user3",
  "pwd": "aaaaaa"
}

### login
POST {{url}}/login
{{json}}

{
  "uname": "user3",
  "pwd": "aaaaaa"
}

### article
POST {{url}}/article/a/123456

### add article
POST {{url}}/article/add
{{cookie}}
folderId: 5ebce656640693b620fa1cfe
