@url = http://localhost:3000/api
@json = Content-Type: application/json

### regsiter
POST {{url}}/register
{{json}}

{
  "uname": "user3",
  "pwd": "aaaaaa"
}

### login
POST {{url}}/login
{{json}}

{
  "uname": "user3",
  "pwd": "aaaaaa"
}

### article
POST {{url}}/article/a/123456
Authorization: berear 544564654651
